"""Build a source-linked, clinician-reviewable brief from fixed analysis output.

The brief is a deterministic handoff contract. It prepares the evidence and
questions for review; it does not diagnose, prescribe, or replace a visit.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any


def _source_ledger(analysis: dict[str, Any]) -> list[dict[str, Any]]:
    dataset = analysis["dataset"]
    quality = analysis["quality"]
    laboratory = analysis.get("longevity_snapshot") or {}
    genomics = analysis.get("genomics_context") or {}
    return [
        {
            "id": "wearables",
            "label": "Wearable recovery record",
            "status": f'{dataset["recorded_days"]} recorded days',
            "fields": ["nightly HRV", "sleep duration", "resting heart rate"],
            "provenance": "Synthetic daily record generated by liveforever_lab.synthetic.",
        },
        {
            "id": "habit_log",
            "label": "Caffeine and context log",
            "status": f'{quality["paired_days"]} paired nights',
            "fields": ["caffeine timing", "daily dose", "training", "alcohol"],
            "provenance": "Synthetic habit fields paired with the following night's outcome by date.",
        },
        {
            "id": "laboratory",
            "label": "Laboratory context",
            "status": laboratory.get("completeness", "Not supplied for this run"),
            "fields": ["published PhenoAge inputs"],
            "provenance": "Synthetic laboratory fixture; contextual only and not used in the caffeine effect estimate.",
        },
        {
            "id": "genomics",
            "label": "Genomic hypothesis context",
            "status": genomics.get("confidence", "Not supplied for this run"),
            "fields": [genomics.get("gene", "CYP1A2 marker not supplied")],
            "provenance": "Synthetic marker context; used to prioritize a question, never to determine the result.",
        },
    ]


def build_care_brief(
    analysis: dict[str, Any], plan: dict[str, Any]
) -> dict[str, Any]:
    """Return an immutable-evidence brief for a user-controlled clinical handoff."""
    primary = analysis["primary_effect"]
    secondary = analysis["secondary_effects"]
    quality = analysis["quality"]
    paired_days = primary["n_on"] + primary["n_off"]

    return {
        "schema_version": "1.0",
        "title": "Personal evidence brief",
        "persona": analysis["dataset"]["persona"],
        "review_status": "Draft for clinician review; not medical advice.",
        "privacy": {
            "record_type": "synthetic",
            "contains_phi": False,
            "sharing_control": "User reviews and exports the brief; nothing is transmitted by the demo.",
        },
        "visit_question": analysis["question"],
        "why_this_visit": (
            f"A repeated within-person comparison across {paired_days} paired nights found "
            "a recovery pattern worth discussing and prospectively retesting."
        ),
        "evidence_summary": {
            "analysis_type": analysis["analysis_type"],
            "data_window": {
                "start_date": analysis["dataset"]["start_date"],
                "end_date": analysis["dataset"]["end_date"],
                "recorded_days": analysis["dataset"]["recorded_days"],
            },
            "primary_effect": deepcopy(primary),
            "secondary_effects": deepcopy(secondary),
            "quality": deepcopy(quality),
        },
        "plain_language_signal": (
            f"Cutoff days were followed by {primary['effect']:+.2f} ms higher nightly HRV on average "
            f"(95% interval {primary['ci_low']:+.2f} to {primary['ci_high']:+.2f}; "
            f"{primary['n_on']} cutoff and {primary['n_off']} usual-timing nights)."
        ),
        "source_ledger": _source_ledger(analysis),
        "uncertainty": [
            "The comparison is observational and does not establish that caffeine timing caused the differences.",
            "Missing days, concurrent behaviors, illness, travel, stress, and device noise may influence the result.",
            f"The evidence-quality grade is {quality['grade']} ({quality['score']}/100), and all quality warnings remain attached.",
            "Genomic and laboratory context can prioritize a question but cannot validate the observed association.",
        ],
        "missing_evidence": [
            "A prospectively registered replication with balanced conditions and adherence tracking.",
            "Symptom, medication, illness, travel, and major schedule context reviewed for the same dates.",
            "Confirmation that the wearable trend is meaningful for this person in the broader clinical context.",
        ],
        "questions_for_clinician": [
            "Is this magnitude and pattern meaningful in the context of the person's history and symptoms?",
            "What clinical or behavioral context could offer a more likely explanation for the observed pattern?",
            "Are there reasons a caffeine-timing retest would be inappropriate or should be modified?",
            "What additional measurements would make a future comparison more useful for review?",
        ],
        "proposed_next_step": {
            "title": plan["title"],
            "design": plan["design"],
            "decision_rule": plan["decision_rule"],
            "controls": deepcopy(plan["controls"]),
            "status": "Discuss before starting; this is an experiment draft, not a treatment plan.",
        },
        "ai_contract": {
            "role": "Turn the locked evidence into a concise, source-linked draft and prepare questions for human review.",
            "immutable_paths": [
                "evidence_summary.primary_effect",
                "evidence_summary.secondary_effects",
                "evidence_summary.quality",
                "source_ledger",
            ],
            "allowed_actions": [
                "Explain fixed results in plain language.",
                "Identify uncertainty, missing context, and alternative hypotheses.",
                "Organize questions for a clinician and shorten the draft after user review.",
            ],
            "forbidden_actions": [
                "Do not diagnose a condition.",
                "Do not prescribe treatment or change medication or supplements.",
                "Do not alter, recompute, omit, or invent evidence values or sources.",
                "Do not convert an association into a causal or clinical claim.",
            ],
            "human_gate": "The user reviews every field and chooses whether to export or share it.",
        },
    }
